export const SYMBOL_NAMES: Record<string, string> = {
  // 나스닥 지수/선물
  '^KS11': 'KOSPI',
  '^KQ11': 'KOSDAQ',
  'NQ=F':  '나스닥선물',

  // 나스닥 개별종목
  'AMAT':  '어플라이드머티리얼즈',
  'BKNG':  '부킹홀딩스',
  'ISRG':  '인튜이티브서지컬',
  'MU':    '마이크론테크놀로지',
  'LRCX':  '램리서치',
  'ADI':   '아날로그디바이시스',
  'KLAC':  'KLA',
  'PANW':  '팔로알토네트웍스',
  'GILD':  '길리어드사이언스',
  'MDLZ':  '몬델리즈',
  'REGN':  '리제너론',
  'CDNS':  '케이던스디자인',
  'SNPS':  '시놉시스',
  'ASML':  'ASML',
  'MRVL':  '마벨테크놀로지',
  'ORLY':  '오라일리오토모티브',
  'CRWD':  '크라우드스트라이크',
  'CTAS':  '신타스',
  'MNST':  '몬스터베버리지',
  'ABNB':  '에어비앤비',
  'MELI':  '메르카도리브레',
  'WDAY':  '워크데이',
  'FTNT':  '포티넷',
  'CPRT':  '코파트',
  'PCAR':  '팩카',
  'ADP':   'ADP',
  'ROST':  '로스스토어스',
  'KDP':   '큐리그닥터페퍼',
  'DXCM':  '덱스콤',
  'FANG':  '다이아몬드백에너지',
  'IDXX':  '아이덱스래보러토리스',
  'VRSK':  '버리스크',
  'BIIB':  '바이오젠',
  'EXC':   '엑셀론',
  'XEL':   '엑셀에너지',
  'AEP':   '아메리칸일렉트릭파워',
  'ON':    'ON세미컨덕터',
  'FAST':  '패스널',
  'CTSH':  '코그니전트',
  'CDW':   'CDW',
  'TEAM':  '아틀라시안',
  'DDOG':  '데이터독',
  'ZS':    '지스케일러',
  'ILMN':  '일루미나',
  'NXPI':  'NXP세미컨덕터스',
  'LULU':  '룰루레몬',
  'VRSN':  '베리사인',
  'DLTR':  '달러트리',
  'ALGN':  '얼라인테크놀로지',
  'CEG':   '콘스텔레이션에너지',
  'TTD':   '더트레이드데스크',
  'ENPH':  '엔페이즈에너지',
  'CSX':   'CSX',
  'CHTR':  '차터커뮤니케이션스',
  'EBAY':  '이베이',
  'PAYX':  '페이첵스',
  'KHC':   '크래프트하인즈',
  'MRNA':  '모더나',
  'SBUX':  '스타벅스',
  'CMCSA': '컴캐스트',
  'PEP':   '펩시코',
  'TMUS':  'T모바일',
  'CSCO':  '시스코',
  'MCHP':  '마이크로칩테크',
  'ANSS':  '앤시스',
  'HON':   '허니웰',
  'EA':    'EA(일렉트로닉아츠)',
  'MAR':   '메리어트',
  'PYPL':  '페이팔',
  'ODFL':  '올드도미니언프레이트',
  'GEHC':  'GE헬스케어',
  'PLTR':  '팔란티어',
  'ARM':   'ARM홀딩스',
  'DASH':  '도어대시',
  'AXON':  '액손엔터프라이즈',
  'ROP':   '로퍼테크',
  'SMCI':  '슈퍼마이크로컴퓨터',
  'WBD':   '워너브라더스',
  'SIRI':  '시리우스XM',
  'GFS':   '글로벌파운드리즈',
  'OKTA':  '옥타',

  // 한국 개별종목
  '005930.KS': '삼성전자',
  '000660.KS': 'SK하이닉스',
  '035420.KS': 'NAVER',
  '035720.KS': '카카오',
  '051910.KS': 'LG화학',
  '006400.KS': '삼성SDI',
  '207940.KS': '삼성바이오로직스',
  '068270.KS': '셀트리온',
  '003550.KS': 'LG',
  '105560.KS': 'KB금융',
};

/** symbol → 한국어 이름 반환. 없으면 symbol 그대로 반환 */
export function getSymbolName(symbol: string): string {
  return SYMBOL_NAMES[symbol] ?? symbol;
}
